# Generated by Django 5.0.14 on 2026-07-31 08:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('county', models.CharField(blank=True, default='', max_length=60)),
                ('level', models.CharField(blank=True, default='', max_length=60)),
                ('maternity_unit_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', max_length=120)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facilities_facility',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('shift_pattern', models.CharField(blank=True, default='', max_length=120)),
                ('max_students', models.IntegerField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facilities_ward',
            },
        ),
    ]
