# Generated by Django 5.0.14 on 2026-07-31 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='identity.program'),
        ),
        migrations.AddField(
            model_name='ward',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='ward',
            name='nurse_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_wards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.CheckConstraint(check=models.Q(('max_students__gt', 0)), name='ward_capacity_positive'),
        ),
    ]
