# Generated by Django 5.0.14 on 2026-07-31 08:48

import apps.core.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_extensions"),
        ('facilities', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('awaiting_student', 'Awaiting Student'), ('orientation', 'Orientation'), ('induction', 'Induction'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived'), ('withdrawn', 'Withdrawn')], default='draft', max_length=24)),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('withdrawal_reason', models.CharField(blank=True, choices=[('student_withdrew', 'Student withdrew'), ('academic_decision', 'Academic decision'), ('facility_capacity', 'Facility capacity'), ('safeguarding', 'Safeguarding'), ('administrative_error', 'Administrative error'), ('other', 'Other')], max_length=32, null=True)),
                ('withdrawal_note', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='institutions.cohort')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_placements', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='facilities.facility')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='institutions.institution')),
            ],
            options={
                'db_table': 'placements_placement',
            },
        ),
        migrations.CreateModel(
            name='PauseInterval',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('student_illness', 'Student illness'), ('personal_family', 'Personal or family'), ('industrial_action', 'Industrial action'), ('facility_closure', 'Facility closure'), ('ward_capacity', 'Ward capacity'), ('academic_examinations', 'Academic or examinations'), ('mentor_unavailability', 'Mentor unavailability'), ('safeguarding_investigation', 'Safeguarding investigation'), ('public_health_emergency', 'Public health emergency'), ('other', 'Other')], max_length=40)),
                ('reason_note', models.TextField(blank=True, null=True)),
                ('paused_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pauses', to='placements.placement')),
            ],
            options={
                'db_table': 'placements_pause_interval',
            },
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, default='', max_length=120)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor_assignments', to='placements.placement')),
            ],
            options={
                'db_table': 'placements_mentor_assignment',
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, default='', max_length=120)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='placements.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placements_student_assignment',
            },
        ),
        migrations.CreateModel(
            name='WardAssignment',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, default='', max_length=120)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ward_assignments', to='placements.placement')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ward_assignments', to='facilities.ward')),
            ],
            options={
                'db_table': 'placements_ward_assignment',
            },
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['institution', 'state'], name='placements__institu_be08d7_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['facility', 'state'], name='placements__facilit_e38692_idx'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.CheckConstraint(check=models.Q(('planned_start__lt', models.F('planned_end'))), name='planned_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.CheckConstraint(check=models.Q(('actual_end', None), ('actual_start', None), ('actual_start__lte', models.F('actual_end')), _connector='OR'), name='actual_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('state', 'withdrawn'), _negated=True), models.Q(('withdrawal_reason', None), _negated=True), _connector='OR'), name='withdrawn_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('state', 'completed'), _negated=True), models.Q(('completed_at', None), _negated=True), _connector='OR'), name='completed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='pauseinterval',
            constraint=models.CheckConstraint(check=models.Q(('ended_on', None), ('started_on__lte', models.F('ended_on')), _connector='OR'), name='pause_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='pauseinterval',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_on', None)), fields=('placement',), name='one_open_pause_per_placement'),
        ),
        migrations.AddConstraint(
            model_name='pauseinterval',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('placement'), '='), (models.Func(models.F('started_on'), models.F('ended_on'), models.Value('[)'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='pause_no_overlap'),
        ),
        migrations.AddIndex(
            model_name='mentorassignment',
            index=models.Index(condition=models.Q(('ended_at', None)), fields=['mentor'], name='mentor_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at', None)), fields=('placement',), name='one_active_mentor_per_placement'),
        ),
        migrations.AddConstraint(
            model_name='studentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at', None)), fields=('placement',), name='one_active_student_per_placement'),
        ),
        migrations.AddConstraint(
            model_name='studentassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('student'), '='), (models.Func(models.F('started_on'), models.F('ended_on'), models.Value('[)'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='student_no_overlapping_placements'),
        ),
        migrations.AddConstraint(
            model_name='wardassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at', None)), fields=('placement',), name='one_active_ward_per_placement'),
        ),
    ]
