# Generated by Django 5.0.14 on 2026-07-31 08:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_role', models.CharField(max_length=32)),
                ('scope', models.JSONField(default=dict)),
                ('action', models.CharField(max_length=64)),
                ('entity_table', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('is_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_audit_entry',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('command_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(max_length=64)),
                ('result_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_idempotency_key',
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_outbox_event',
            },
        ),
    ]
