# Generated by Django 5.0.14 on 2026-07-31 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(condition=models.Q(('dispatched_at', None)), fields=['occurred_at'], name='outbox_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['entity_table', 'entity_id', '-occurred_at'], name='core_audit__entity__c56401_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['actor', '-occurred_at'], name='core_audit__actor_i_d65538_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditentry',
            constraint=models.CheckConstraint(check=models.Q(('is_override', False), models.Q(('override_reason', None), _negated=True), _connector='OR'), name='audit_override_needs_reason'),
        ),
    ]
