# Generated by Django 5.0.14 on 2026-07-31 08:48

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='identity.program')),
            ],
            options={
                'db_table': 'induction_checklist_template',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='induction_checklist', to='placements.placement')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_checklists', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='induction.checklisttemplate')),
            ],
            options={
                'db_table': 'induction_checklist',
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.SmallIntegerField()),
                ('label', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('completed_by_role', models.CharField(default='mentor', max_length=32)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='induction.checklisttemplate')),
            ],
            options={
                'db_table': 'induction_template_item',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ItemResponse',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not applicable')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='induction.checklist')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='induction.templateitem')),
            ],
            options={
                'db_table': 'induction_item_response',
            },
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('program', 'version'), name='one_template_version_per_program'),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.CheckConstraint(check=models.Q(('completed_at', None), models.Q(('signed_by', None), _negated=True), _connector='OR'), name='checklist_completed_needs_signature'),
        ),
        migrations.AddConstraint(
            model_name='templateitem',
            constraint=models.UniqueConstraint(fields=('template', 'position'), name='one_item_per_position'),
        ),
        migrations.AddConstraint(
            model_name='itemresponse',
            constraint=models.UniqueConstraint(fields=('checklist', 'template_item'), name='one_response_per_item'),
        ),
    ]
