# Generated by Django 5.0.14 on 2026-07-31 08:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('baseline_confidence', 'Baseline confidence'), ('final_confidence', 'Final confidence'), ('exit_survey', 'Exit survey')], max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessments_assessment',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnonymous',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_on', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessments_feedback_anonymous',
            },
        ),
        migrations.CreateModel(
            name='FeedbackConfidential',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('unresolved_concern', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessments_feedback_confidential',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_code', models.CharField(max_length=60)),
                ('scale', models.CharField(choices=[('likert_1_5', 'Likert 1-5'), ('score_0_100', 'Score 0-100'), ('yes_no', 'Yes/No')], max_length=20)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessments_response',
            },
        ),
    ]
