# Generated by Django 5.0.14 on 2026-07-31 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('facilities', '0001_initial'),
        ('institutions', '0001_initial'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='placements.placement'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='revises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='feedbackanonymous',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anonymous_feedback', to='institutions.cohort'),
        ),
        migrations.AddField(
            model_name='feedbackanonymous',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anonymous_feedback', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='feedbackanonymous',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anonymous_feedback', to='facilities.ward'),
        ),
        migrations.AddField(
            model_name='feedbackconfidential',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='placements.placement'),
        ),
        migrations.AddField(
            model_name='feedbackconfidential',
            name='revises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assessments.feedbackconfidential'),
        ),
        migrations.AddField(
            model_name='response',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='response',
            name='feedback_anonymous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.feedbackanonymous'),
        ),
        migrations.AddField(
            model_name='response',
            name='feedback_confidential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.feedbackconfidential'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['placement', 'kind'], name='assessments_placeme_018a45_idx'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('scale', 'likert_1_5'), ('value_numeric__gte', 1), ('value_numeric__lte', 5)), models.Q(('scale', 'score_0_100'), ('value_numeric__gte', 0), ('value_numeric__lte', 100)), models.Q(('scale', 'yes_no'), ('value_boolean__isnull', False), ('value_numeric', None)), _connector='OR'), name='assessment_score_in_range'),
        ),
    ]
