# Generated by Django 5.0.14 on 2026-07-31 08:48

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('planned_capacity', models.IntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institutions_cohort',
            },
        ),
        migrations.CreateModel(
            name='CohortMembership',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='institutions.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohort_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institutions_cohort_membership',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=60)),
                ('county', models.CharField(blank=True, default='', max_length=60)),
                ('contact_person', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='identity.program')),
            ],
            options={
                'db_table': 'institutions_institution',
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='institutions.institution'),
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('cohort', 'student'), name='one_membership_per_cohort'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='cohort_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(check=models.Q(('planned_capacity', None), ('planned_capacity__gt', 0), _connector='OR'), name='cohort_capacity_positive'),
        ),
    ]
