# Generated by Django 5.0.14 on 2026-07-31 08:48

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=60)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('action_required', 'Action required'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('finding', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='facilities.facility')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='placements.placement')),
                ('related_escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='safeguarding.escalation')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_escalations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safeguarding_escalation',
                'indexes': [models.Index(condition=models.Q(('state', 'closed'), _negated=True), fields=['facility', 'severity'], name='escalation_open_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='escalation',
            constraint=models.CheckConstraint(check=models.Q(('reviewer', None), models.Q(('reviewer', models.F('submitted_by')), _negated=True), _connector='OR'), name='reviewer_is_not_submitter'),
        ),
        migrations.AddConstraint(
            model_name='escalation',
            constraint=models.CheckConstraint(check=models.Q(('state', 'open'), models.Q(('reviewer', None), _negated=True), _connector='OR'), name='non_open_needs_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='escalation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('state__in', ['resolved', 'closed']), _negated=True), models.Q(('action_taken', None), _negated=True), _connector='OR'), name='resolved_needs_action'),
        ),
        migrations.AddConstraint(
            model_name='escalation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('state', 'closed'), _negated=True), models.Q(('closure_date', None), _negated=True), _connector='OR'), name='closed_needs_date'),
        ),
    ]
