# Generated by Django 5.0.14 on 2026-07-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_one_organisation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.AddField(
            model_name='user',
            name='facility_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='institution_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('facility_id', None), ('institution_id', None), ('role', 'program_admin')), models.Q(('facility_id', None), ('institution_id__isnull', False), ('role__in', ['student', 'coordinator'])), models.Q(('facility_id__isnull', False), ('institution_id', None), ('role__in', ['mentor', 'nurse_manager'])), _connector='OR'), name='user_one_organisation'),
        ),
    ]
