# Generated by Django 5.0.14 on 2026-07-31 08:48

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField()),
                ('session_type', models.CharField(choices=[('orientation', 'Orientation'), ('bedside_teaching', 'Bedside teaching'), ('skills_discussion', 'Skills discussion'), ('debrief', 'Debrief'), ('feedback', 'Feedback'), ('case_reflection', 'Case reflection'), ('other', 'Other')], max_length=32)),
                ('duration_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('what_was_covered', models.TextField(blank=True, null=True)),
                ('feedback_given', models.TextField(blank=True, null=True)),
                ('follow_up_action', models.CharField(blank=True, default='', max_length=120)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrects', to='mentorship.session')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentor_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='placements.mentorassignment')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='placements.placement')),
            ],
            options={
                'db_table': 'mentorship_session',
            },
        ),
        migrations.CreateModel(
            name='SessionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=60)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mentorship.session')),
            ],
            options={
                'db_table': 'mentorship_session_topic',
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['placement', '-session_date'], name='mentorship__placeme_44dd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['mentor_assignment', 'session_date'], name='mentorship__mentor__2fd9bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes', None), models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 480)), _connector='OR'), name='session_duration_sane'),
        ),
        migrations.AddConstraint(
            model_name='sessiontopic',
            constraint=models.UniqueConstraint(fields=('session', 'topic'), name='one_row_per_session_topic'),
        ),
    ]
