# Generated by Django 5.0.14 on 2026-07-31 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_constraints'),
        ('placements', '0002_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='submitted_bucket',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('placement', 'mentor_assignment', 'session_date', 'submitted_bucket'), name='session_no_duplicate_within_window'),
        ),
    ]
